### ISSUE TITLE
cpbd.demos.sr examples  do not work (windows)

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#20]
C:\Users\iagapov\workspace\ocelot/lib/genera/build/genera_libs/undulator.so
platform =  win32   os.name =  nt
Traceback (most recent call last):
  File "C:\Users\iagapov\workspace\ocelot\demos\sr\spatial.py", line 5, in <module>
    from ocelot.lib.genera.src.python.radiation import generaSR
  File "C:\Users\iagapov\workspace\ocelot\lib\genera\src\python\radiation\generaSR.py", line 6, in <module>
    from ocelot.lib.genera.src.python.trajectory.lat_trajectory import trace4radiation
  File "C:\Users\iagapov\workspace\ocelot\lib\genera\src\python\trajectory\lat_trajectory.py", line 2, in <module>
    from undulator import und_trace
  File "C:\Users\iagapov\workspace\ocelot\lib\genera\src\python\trajectory\undulator.py", line 40, in <module>
    exec(open(path_to_ocelot + "/lib/genera/src/cpp/compile.py"))
  File "C:\Users\iagapov\workspace\ocelot/lib/genera/src/cpp/compile.py", line 73, in <module>
    compile(dir_path)
  File "C:\Users\iagapov\workspace\ocelot/lib/genera/src/cpp/compile.py", line 33, in compile
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Python27\lib\subprocess.py", line 709, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by sergey-tomin** [comment]
added examples used "pure python".
