### ISSUE TITLE
demos.optics.ex6.py does not work

### ISSUE THREAD

**Issue by sergey-tomin** [iagapov/ocelot#36]
Traceback (most recent call last):
  File "C:/Users/tomins/Documents/Dropbox/DESY/repository/ocelot/demos/optics/ex6.py", line 92, in <module>
    s2 = fwhm(x,np.abs(of.mesh.points[:,of.ny/2]))
  File "C:\Users\tomins\Documents\Dropbox\DESY\repository\ocelot\common\math_op.py", line 126, in fwhm
    return x[downs[-1]] - x[ups[0]]
IndexError: list index out of range

**Comment by sergey-tomin** [comment]
Please fix or remove it
