### ISSUE TITLE
desy.demos.ebeam.track_flash2 crashes

### ISSUE THREAD

**Issue by iagapov** [iagapov/ocelot#46]
charge =  1e-09
Traceback (most recent call last):
  File "track_flash2.py", line 40, in <module>
    p_array, charge_array = astra_beam2particleArray(filename='elegant_files/flash_out_200000.ast')
  File "/data/netapp/xfel/products/test/ocelot/adaptors/astra2ocelot.py", line 50, in astra_beam2particleArray
    xxstg = exact_xp_2_xxstg(xp, gamref)
  File "/data/netapp/xfel/products/test/ocelot/adaptors/astra2ocelot.py", line 13, in exact_xp_2_xxstg
    u = u/np.linalg.norm(u, 2, 1).reshape((N, 1))
TypeError: norm() takes at most 2 arguments (3 given)
[iagapov@it-hpc-wgs01]/data/netapp/xfel/products/desy/demos/ebeam/flash%

**Comment by iagapov** [comment]
due to older numpy version (1.6)
will not fix
